web:
  build: .
  dockerfile: web.dockerfile
  links:
    - db:mariadb
  env_file:
    - server_name.env
  ports:
    - 80:80
    - 9000:9000
  volumes:
    - ./www:/var/www/wordpress

db:
  build: .
  dockerfile: db.dockerfile
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - 3306:3306
